## Assignment 2 (Data Science Tools and Techniqes, AM609)
## Reg. No: 24-14-16
## Name: Chandan Maity
## Course: M.Tech Modelling & Simulation

###

### Q1: a) Create a variable named var1 that stores an array of numbers from 0 to 30, inclusive. Print var1 and its shape. 

### b) Change var1 to a validly-shaped two dimensional matrix and store it in a new variable called var2. Print var2 and its shape.

### c) Create a third variable, var3 that reshapes var2 into a valid three dimensional shape. Print var3 and its shape.

### d) Use two dimensional array indexing to set the first value in the second row of var2 to -1. Now look at var1 and var3. Did they change? Explain what's going on. (Hint: Does reshape return a view or a copy?)

### e) Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific dimensions. Figure out how the Numpy sum function works (and the axis argument in particular) and do the following:
### (i) Sum var3 over its second dimension and print the result.                                                                (ii) Sum var3 over its third dimension and print the result.                                                                (iii) Sum var3 over both its first and third dimension and print the result.

### f) Write code to the following: (i) Slice out the second row of var2 and print it.                                                                          (ii) Slice out the last column of var2 using -1 notation and print it.                                                      (iii) Slice out the top right 2 x 2 submatrix of var2 and print it.

In [37]:
import numpy as np

var1=np.arange(0,31)
print("The required array is: ")
print(var1)
print("Shape of the array is: ",var1.shape)
print(    )


var=np.delete(var1,0)
var2=var.reshape(5,-1)
print("The new two dimensional matrix is:")
print(var2)
print("Shape of the matrix is: ",var2.shape)
print(    )


var3=var2.reshape(2,3,-1)
print("The three dimensional shape of variable 3 is: ")
print(var3)
print("Shape of the variable 3 is: ", var3.shape)
print(    )


var2[1,0]=-1
print("Updated var2 is:")
print(var2)
print("Array var1 after modifying var2:")
print(var1)
print("Array var3 after modifying var2:")
print(var3)
print(     )
"""Here we saw that the variable1(var1) is still unchanged while the first element of variable3(var3) is changed to -1. """


sum_var3_dim2 = var3.sum(axis=1)
print("Sum of var3 over its second dimension:\n", sum_var3_dim2)
sum_var3_dim3 = var3.sum(axis=2)
print("Sum of var3 over its third dimension:\n", sum_var3_dim3)
sum_var3_dim4=var3.sum(axis=(0,2))
print("Sum of var3 over its first and third dimension:\n", sum_var3_dim4)
print(     )


row2_of_var2=var2[1:2,]
print("The second row of var2 is: ")
print(row2_of_var2)
col_last_var2=var2[:,-1:]
print("The last column of var2 is: ")
print(col_last_var2)
mat=var2[0:2,4:]
print("The top right 2x2 submatrix of var2 is: ")
print(mat)

The required array is: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape of the array is:  (31,)

The new two dimensional matrix is:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Shape of the matrix is:  (5, 6)

The three dimensional shape of variable 3 is: 
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
Shape of the variable 3 is:  (2, 3, 5)

Updated var2 is:
[[ 1  2  3  4  5  6]
 [-1  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Array var1 after modifying var2:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Array var3 after modifying var2:
[[[ 1  2  3  4  5]
  [ 6 -1  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]

Sum of var3 over its second dimension:
 [[18 13 24 27 30]
 [63 66 

#

#

### Q2: a) The most basic kind of broadcast is with a scalar, in which you can perform a binary operation (e.g., add, multiply,...) on an array and a scalar, the effect is to perform the operation with the scalar for every element of the array. To try this out, create a vector 1,2,3,...,10 by adding 1 to the result of the arange function.

In [10]:
import numpy as np
vector=np.arange(10)
vector+=1
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


###

### b) Now, create a 10 x 10 matrix A in which A_(ij)=i+j. You'll be able to do this using the vector you just created, and adding it to a reshaped veesion of itself.

In [27]:
A = vector.reshape(10, 1) + vector
print("Matrix A:")
print(A)

Matrix A:
[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


###

### c) A very common use of broadcasting is to standardize data, i.e., to make it have zero mean and unit variance. First, create a fake "data set" with 50 examples, each with five dimensions.

In [93]:
import numpy.random as npr
data = np.exp(npr.randn ( 50 ,   5 ) )
print("\nData Matrix:")
print(data)


Data Matrix:
[[ 0.37345545  0.42735162  0.59664014  1.02792155  3.35560869]
 [ 0.31549176  0.72285504 24.5421748   3.67114331  0.45567388]
 [ 1.90287704  1.17193531  1.00245654  1.9047736   0.48183805]
 [ 1.67460926  1.59229386  0.65357928  8.07777693  0.57973248]
 [ 0.44447277  0.40383535  0.98490949  9.33395673  0.25054442]
 [ 0.64396755  1.02249669  2.74003256  5.66175294  1.9406102 ]
 [ 5.40689302  0.84375236 12.71398607  0.33749698  0.6996163 ]
 [ 9.25769712  2.71382823  2.39570534  1.65165788  0.96990477]
 [ 1.31576072  0.82329253  0.32231087  0.13267433  0.6461229 ]
 [ 0.38755208  0.67141177  3.96774712  2.50208841  1.45757005]
 [ 5.41509721  0.82396387  0.96239386  1.63923164  0.22089032]
 [ 4.40556674  2.21382615  1.18650045  0.9288702   0.93660654]
 [10.93491663  0.9513993  10.07913604  0.94319831  0.6154226 ]
 [ 0.45545356  2.76633863  1.75399509  0.61382956  4.48915925]
 [ 0.81486386  1.20089799  2.37812789  0.17708924  0.21203494]
 [ 2.43554138  0.34262375  0.52411235  0.

#### You don't worry too much about what this code is doing at this stage of the course, but for completeness: it imports the Numpy random number generation library, then generates a 50 x 5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend data set of 50 independent and identically-distributed vectors from a log-normal distributions.

###

### e) Now, compute the mean and standard deviation of each column. This should result in two vectors of length 5. You'll need to think a little bit about how to use the axis argument to mean and std. Store these vectors into variables and print both of them.

In [95]:
mean_vector = np.mean(data, axis=0)
std_vector = np.std(data, axis=0)
print("Mean vector:", mean_vector)
print("Standard deviation vector:", std_vector)


Mean vector: [2.4044324  1.51262229 2.33772532 1.53984757 1.54430952]
Standard deviation vector: [3.18823558 1.79885693 3.97756557 2.07994244 1.49917009]


###

### f) Now, Standardize the data matrix by 1) subtracting the mean off of each column and 2) dividing each column by its standard deviation. Do this via broadcasting, and store the result in a matrix called normalized. To verify that you successfully did it, compute the mean and standard deviation of the columns of the normalized and print it. 

In [101]:
normalized = (data - mean_vector) / std_vector
normalized_mean = np.mean(normalized, axis=0)
normalized_std = np.std(normalized, axis=0)
print("\nMean of normalized columns:\n", normalized_mean)
print("\nStandard deviation of normalized columns:\n", normalized_std)


Mean of normalized columns:
 [-1.49602553e-16  2.30926389e-16 -4.44089210e-18  1.29896094e-16
 -8.88178420e-18]

Standard deviation of normalized columns:
 [1. 1. 1. 1. 1.]


#

#

### Q3: a) A Vandermode matrix is a matrix generated from a vector in which each column of the matrix is an integer power starting from zero. Use what you learned about broadcasting in the previous problem to write a function that will produce a Vandermonde matrix for a vector [ 1, 2, ... , N]^T for any N. Do it without using any loop. 

In [76]:
import numpy as np

def vandermonde(N):
    vec = np.arange(N) + 1 
    vec1 = np.arange(N)
    vec2= vec[:, np.newaxis]
    vander_matrix = vec2 ** vec1.astype(dtype="int64")
    return vander_matrix

vander = vandermonde(12)
print(vander)


[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362797056]
 [           1        

###

### b) Now, let's make a pretend linear system problem with this matrix. Create a vector of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of vander with the vector you just created and store that in a new vector and call it b. Print the vector b.

In [78]:
x = np.ones(12)
b= np.dot(vander, x)
print(b)

[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09
 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


###

### c) First solve the linear system the naive way, pretending like you don't know x. Import numpy.linalg, invert V and multiply it by b. Print out your result. What should you get for your answer? If the answer is different than what you expected, write a sentence about that difference.

In [80]:
V = np.linalg.inv(vander)
x1= np.dot(V, b)
print(x1)

[ 105.49609375 -129.88085938   30.39453125   -2.21679688    1.2265625
    0.97705078    1.00299072    0.99966431    1.00002718    0.9999986
    1.00000004    1.        ]


###

### d) Now, solve the same linear system using solve. Print out the result. Does it seem more or less in line with what you'd expect?

In [74]:
x_solve_method = np.linalg.solve(vander, b)
print("Solution to the linear system using np.linalg.solve:\n", x_solve_method)

Solution to the linear system using np.linalg.solve:
 [1.00000064 0.99999871 1.00000078 0.99999993 0.99999989 1.00000005
 0.99999999 1.         1.         1.        ]
